### ISSUE TITLE
.txt --> .tsv for some ancillary data files

### ISSUE THREAD

**Issue by standage** [standage/genhub#71]
Some of the plain text supporting data files in each genome's directory are in fact simply tab-separated value (TSV) files that lack a header row. There isn't really a compelling reason for these files not to have self-documenting headers, which in turn facilitate easy loading into R/Python/etc for data analysis.
- [x] `*.ilocus.mrnas.txt` (this will probably require a change to AEGeAn's `pmrna` program)
- [x] `*.protein2ilocus.txt` (this is internal to GenHub)

Anything I'm missing or any other comments @vpbrendel @cycoyuk?

**Comment by vpbrendel** [comment]
Correct.  There are three other *.txt files, but they are single column and the content is obvious from the file name (and of course, there is never a need to join those ...).
There are also three files with .temp extension which presumably can be deleted in a cleanup step?

**Comment by standage** [comment]
The `fidibus` program does have a cleanup step already implemented, but honestly I haven't given it much attention. By default, it deletes lots of the intermediate files (including the temp files) and leaves the final .tsv files, the iLocus-related GFF3 (and sequence?) files, and the compressed data downloaded from the primary source (such as RefSeq). There's also an option to delete these compressed primary data files too.

This task was optimized for clearing storage space, not file clutter. Any suggestions are welcome. I'd recommend testing the behavior of `fidibus cleanup` on a small genome like _S. cerevisiae_ (label `Scer`) for which the files can be quickly built, cleaned up, and re-built for comparison.
